### Create new TODO
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "content": "test"
}

### Get all TODOs
GET http://localhost:3000/api/todos
Content-Type: application/json

### Mark todo as done
PATCH http://localhost:3000/api/todos/done/:id
Content-Type: application/json

### Delete todo
DELETE http://localhost:3000/api/todos/:id
Content-Type: application/json